import type { ShoppingItem } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [items, setItems] = useState<ShoppingItem[]>([]);

  const {} = trpc.item.addItem.useMutation({
    onSuccess: (item) => {
      setItems((prev) => [...prev, item]);
    },
  });

  return (
    <>
      <Head>
        <title>Shopping List </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">Our Shopping List</h2>
          <button
            type="button"
            className="ml-2 rounded bg-blue-500 p-2 text-sm font-bold text-white hover:bg-blue-600"
          >
            Add list
          </button>
        </div>
        <ul className="mt-4">
          {items.map((item) => (
            <li key={item.id} className="flex items-center justify-between">
              <span>{item.name}</span>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
